// English defaults with Korean translations for language 2.
function lang_en_us(){
	name_instrument_harp = localize_ko("Harp")
	name_instrument_double_bass = localize_ko("Double Bass")
	name_instrument_bass_drum = localize_ko("Bass Drum")
	name_instrument_snare_drum = localize_ko("Snare Drum")
	name_instrument_click = localize_ko("Click")
	name_instrument_guitar = localize_ko("Guitar")
	name_instrument_flute = localize_ko("Flute")
	name_instrument_bell = localize_ko("Bell")
	name_instrument_chime = localize_ko("Chime")
	name_instrument_xylophone = localize_ko("Xylophone")
	name_instrument_iron_xylophone = localize_ko("Iron Xylophone")
	name_instrument_cow_bell = localize_ko("Cow Bell")
	name_instrument_didgeridoo = localize_ko("Didgeridoo")
	name_instrument_bit = localize_ko("Bit")
	name_instrument_banjo = localize_ko("Banjo")
	name_instrument_pling = localize_ko("Pling")

	name_block_color_orange = localize_ko("Orange")
	name_block_color_magenta = localize_ko("Magenta")
	name_block_color_light_blue = localize_ko("Light Blue")
	name_block_color_yellow = localize_ko("Yellow")
	name_block_color_lime = localize_ko("Lime")
	name_block_color_pink = localize_ko("Pink")
	name_block_color_gray = localize_ko("Gray")
	name_block_color_light_gray = localize_ko("Light Gray")
	name_block_color_cyan = localize_ko("Cyan")
	name_block_color_purple = localize_ko("Purple")
	name_block_color_blue = localize_ko("Blue")
	name_block_color_brown = localize_ko("Brown")
	name_block_color_green = localize_ko("Green")
	name_block_color_red = localize_ko("Red")
	name_block_color_black = localize_ko("Black")
	name_block_color_white = localize_ko("White")

	name_block_air = localize_ko("Air")
	name_block_stone = localize_ko("Stone")
	name_block_grass_block = localize_ko("Grass Block")
	name_block_dirt = localize_ko("Dirt")
	name_block_cobblestone = localize_ko("Cobblestone")
	name_block_wood_planks = localize_ko("Wood Planks")
	name_block_bedrock = localize_ko("Bedrock")
	name_block_sand = localize_ko("Dirt")
	name_block_gravel = localize_ko("Gravel")
	name_block_gold_ore = localize_ko("Gold Ore")
	name_block_iron_ore = localize_ko("Iron Ore")
	name_block_coal_ore = localize_ko("Coal Ore")
	name_block_wood = localize_ko("Wood")
	name_block_leaves = localize_ko("Leaves")
	name_block_sponge = localize_ko("Sponge")
	name_block_glass = localize_ko("Glass")
	name_block_lapis_lazuli_ore = localize_ko("Lapis Lazuli Ore")
	name_block_lapis_lazuli_block = localize_ko("Lapis Lazuli Block")
	name_block_dispenser = localize_ko("Dispenser")
	name_block_sandstone = localize_ko("Sandstone")
	name_block_note_block = localize_ko("Note Block")
	name_block_bed = localize_ko("Bed")
	name_block_powered_rail = localize_ko("Powered Rail")
	name_block_detector_rail = localize_ko("Detector Rail")
	name_block_sticky_piston = localize_ko("Sticky Piston")
	name_block_cobweb = localize_ko("Cobweb")
	name_block_piston = localize_ko("Piston")
	name_block_wool = localize_ko("Wool")
	name_block_block_of_gold = localize_ko("Block of Gold")
	name_block_block_of_iron = localize_ko("Block of Iron")
	name_block_bricks = localize_ko("Bricks")
	name_block_tnt = "TNT"
	name_block_bookshelf = localize_ko("Bookshelf")
	name_block_moss_stone = localize_ko("Moss Stone")
	name_block_obsidian = localize_ko("Obsidian")
	name_block_monster_spawner = localize_ko("Monster Spawner")
	name_block_chest = localize_ko("Chest")
	name_block_diamond_ore = localize_ko("Diamond Ore")
	name_block_block_of_diamond = localize_ko("Block of Diamond")
	name_block_crafting_table = localize_ko("Crafting Table")
	name_block_farmland = localize_ko("Farmland")
	name_block_furnace = localize_ko("Furnace")
	name_block_burning_furnace = localize_ko("Burning Furnace")
	name_block_redstone_ore = localize_ko("Redstone Ore")
	name_block_glowing_redstone_ore = localize_ko("Glowing Redstone Ore")
	name_block_snow = localize_ko("Snow")
	name_block_ice = localize_ko("Ice")
	name_block_clay = localize_ko("Clay")
	name_block_pumpkin = localize_ko("Pumpkin")
	name_block_netherrack = localize_ko("Netherrack")
	name_block_soul_sand = localize_ko("Soul Sand")
	name_block_glowstone = localize_ko("Glowstone")
	name_block_jack_o_lantern = localize_ko("Jack - o'Lantern")
	name_block_cake = localize_ko("Cake")
	name_block_stained_glass = localize_ko(" Stained Glass")
	name_block_monster_egg = localize_ko("Monster Egg")
	name_block_stone_bricks = localize_ko("Stone Bricks")
	name_block_brown_mushroom = localize_ko("Brown Mushroom")
	name_block_red_mushroom = localize_ko("Red Mushroom")
	name_block_melon = localize_ko("Melon")
	name_block_mycelium = localize_ko("Mycelium")
	name_block_nether_brick = localize_ko("Nether Brick")
	name_block_end_stone = localize_ko("End Stone")
	name_block_redstone_lamp = localize_ko("Redstone Lamp (inactive)")
	name_block_redstone_lamp_active = localize_ko("Redstone Lamp (active)")
	name_block_wooden_slab = localize_ko("Wooden Slab")
	name_block_emerald_ore = localize_ko("Emerald Ore")
	name_block_block_of_emerald = localize_ko("Block of Emerald")
	name_block_command_block = localize_ko("Command Block")
	name_block_beacon = localize_ko("Beacon")
	name_block_daylight_sensor = localize_ko("Daylight Sensor")
	name_block_block_of_redstone = localize_ko("Block of Redstone")
	name_block_nether_quartz_ore = localize_ko("Nether Quartz Ore")
	name_block_block_of_quartz = localize_ko("Block of Quartz")
	name_block_terracotta = localize_ko("Terracotta")
	name_block_terracotta_color = localize_ko(" Terracotta")
	name_block_leaves2 = localize_ko("Leaves (Acacia / Dark Oak)")
	name_block_wood2 = localize_ko("Wood (Acacia / Dark Oak)")
	name_block_slime_block = localize_ko("Slime Block")
	name_block_prismarine = localize_ko("Prismarine")
	name_block_sea_lantern = localize_ko("Sea Lantern")
	name_block_hay_bale = localize_ko("Hay Bale")
	name_block_block_of_coal = localize_ko("Block of Coal")
	name_block_packed_ice = localize_ko("Packed Ice")
	name_block_red_sandstone = localize_ko("Red Sandstone")
	name_block_purpur_block = localize_ko("Purpur Block")
	name_block_purpur_pillar = localize_ko("Purpur Pillar")
	name_block_end_bricks = localize_ko("End Bricks")
	name_block_grass_path = localize_ko("Grass Path")
	name_block_command_block_repeating = localize_ko("Repeating Command Block")
	name_block_command_block_chain = localize_ko("Chain Command Block")
	name_block_frosted_ice = localize_ko("Frosted Ice")
	name_block_magma_block = localize_ko("Magma Block")
	name_block_nether_wart_block = localize_ko("Nether Wart Block")
	name_block_red_nether_brick = localize_ko("Red Nether Brick")
	name_block_bone_block = localize_ko("Bone Block")
	name_block_concrete = localize_ko("Concrete")
	name_block_concrete_powder = localize_ko("Concrete Powder")

	name_macro_tremolo = localize_ko("Tremolo")
	name_macro_stereo = localize_ko("Stereo")
	name_macro_arpeggio = localize_ko("Arpeggio")
	name_macro_portamento = localize_ko("Portamento")
	name_macro_vibrato = localize_ko("Vibrato")
	name_macro_stagger = localize_ko("Stagger")
	name_macro_chorus = localize_ko("Chorus")
	name_macro_volume_lfo = localize_ko("Volume LFO")
	name_macro_fade_in = localize_ko("Fade in")
	name_macro_fade_out = localize_ko("Fade out")
	name_macro_replace_key = localize_ko("Replace key")
	name_macro_set_velocity = localize_ko("Set velocity")
	name_macro_set_panning = localize_ko("Set panning")
	name_macro_set_pitch = localize_ko("Set pitch")
	name_macro_reset = localize_ko("Reset all properties")

	text_second = localize_ko(" second")
	text_minute = localize_ko(" minute")
	text_hour = localize_ko(" hour")
	text_day = localize_ko(" day")
	text_week = localize_ko(" week")
	text_month = localize_ko(" month")
	text_year = localize_ko(" year")
	text_ago = localize_ko(" ago")
	text_plural = condstr(language != 2, "s")

	text_create_instrument_file_not_found_01 = localize_ko("The following file(s) could not be found:")
	text_create_instrument_file_not_found_02 = localize_ko("Some sounds might not play.")
	text_create_instrument_file_not_found_name = localize_ko("Error")

	text_tutorial_url = "http://www.youtube.com/playlist?list=PL7EA4F0D271DA6E86"
	text_tutorial_url_01 = "http://www.youtube.com/watch?v=2oD9Bw_Qau4"
	text_tutorial_url_02 = "http://www.youtube.com/watch?v=NIxNTK6nfJI"
	text_tutorial_url_03 = "http://www.youtube.com/watch?v=JMPkf7bS8lQ"
	text_tutorial_url_04 = "http://www.youtube.com/watch?v=Cg6dAcEjTs0"

	text_draw_title_unsaved = localize_ko("Unsaved song")
	text_draw_blackout = localize_ko("Blackout mode")
	text_draw_on = localize_ko("ON")
	text_draw_off = localize_ko("OFF")
	text_draw_fullscreen = localize_ko("Fullscreen")
	text_draw_tab_section_01 = localize_ko("Remove section")
	text_draw_tab_section_02 = localize_ko("Jump to beginning of section")
	text_draw_tab_section_03 = localize_ko("Jump to ending of section")
	text_draw_tab_section_04 = localize_ko("Select all blocks in section")
	text_draw_tab_section_05 = localize_ko("Start playing in section")
	text_draw_tab_section_06 = localize_ko("Stop playing after section")
	text_draw_tab_changeto = localize_ko("...to")
	text_draw_tab_more = localize_ko("More...")
	text_draw_tab_editext_01 = localize_ko("Copy")
	text_draw_tab_editext_02 = localize_ko("Cut")
	text_draw_tab_editext_03 = localize_ko("Paste")
	text_draw_tab_editext_04 = localize_ko("Delete")
	text_draw_tab_editext_05 = localize_ko("Select all")
	text_draw_tab_editext_06 = localize_ko("Deselect all")
	text_draw_tab_editext_07 = localize_ko("Invert selection")
	text_draw_tab_editext_08 = localize_ko("Select all to the right")
	text_draw_tab_editext_09 = localize_ko("Select all to the left")
	text_draw_tab_editext_10 = localize_ko("Select all ")
	text_draw_tab_editext_11 = localize_ko("Select all but ")
	text_draw_tab_editext_12 = localize_ko("Change instrument...")
	text_draw_tab_editext_13 = localize_ko("Expand selection")
	text_draw_tab_editext_14 = localize_ko("Compress selection")
	text_draw_tab_editext_15 = localize_ko("Macros...")
	text_draw_tab_editext_16 = localize_ko("Transpose notes outside octave range")
	text_draw_window_scale = localize_ko("Window scale")
	text_draw_rainbow = localize_ko("Rainbow mode")
	text_draw_max_framerate = localize_ko("Max framerate")
	text_draw_expand_workspace = localize_ko("Expand workspace")
	text_draw_return = localize_ko("Return")
	text_draw_layer_name_popup = localize_ko("The name for this layer")
	text_draw_layer_name = localize_ko("The name of this layer.")
	text_draw_layer_num_placeholder = localize_ko("Layer")
	text_draw_layer_num_placeholder_suffix = ""
	text_draw_layer_volume_popup = localize_ko("Volume of this layer: ")
	text_draw_layer_volume_popup_drag = localize_ko("%\n(Click and drag to change)")
	text_draw_stereo_center = localize_ko("Center")
	text_draw_stereo_pan = localize_ko("Stereo pan: ")
	text_draw_stereo_pan_drag = localize_ko("\n(Click and drag to change)")
	text_draw_stereo_mono = localize_ko("MONO")
	text_draw_lock = localize_ko("Lock this layer")
	text_draw_solo = localize_ko("Solo this layer")
	text_draw_sellayer = localize_ko("Select all note blocks in this layer\n(Hold Ctrl to select multiple layers)")
	text_draw_add_layer = localize_ko("Add empty layer here")
	text_draw_remove_layer = localize_ko("Remove this layer")
	text_draw_shift_layer_up = localize_ko("Shift layer up")
	text_draw_shift_layer_down = localize_ko("Shift layer down")
	text_draw_tab_file_name = localize_ko("File")
	text_draw_tab_file_01 = localize_ko("New song")
	text_draw_tab_file_02 = localize_ko("Open song...")
	text_draw_tab_file_03 = localize_ko("Recent songs...")
	text_draw_tab_file_04 = localize_ko("Clear recent songs")
	text_draw_tab_file_05 = localize_ko("No recent songs")
	text_draw_tab_file_06 = localize_ko("Save song")
	text_draw_tab_file_07 = localize_ko("Save song as a new file...")
	text_draw_tab_file_08 = localize_ko("Save options...")
	text_draw_tab_file_09 = localize_ko("Import pattern...")
	text_draw_tab_file_10 = localize_ko("Export pattern...")
	text_draw_tab_file_11 = localize_ko("Import from MIDI...")
	text_draw_tab_file_12 = localize_ko("Import from schematic...")
	text_draw_tab_file_13 = localize_ko("Export as MP3...")
	text_draw_tab_file_14 = localize_ko("Export as schematic...")
	text_draw_tab_file_15 = localize_ko("Export as branch schematic...")
	text_draw_tab_file_16 = localize_ko("Export as data pack...")
	text_draw_tab_file_17 = localize_ko("Exit")
	text_draw_tab_edit_name = localize_ko("Edit")
	text_draw_tab_settings_name = localize_ko("Settings")
	text_draw_tab_settings_01 = localize_ko("Instrument")
	text_draw_tab_settings_02 = localize_ko("Instrument settings...")
	text_draw_tab_settings_03 = localize_ko("Song info...")
	text_draw_tab_settings_04 = localize_ko("Song properties...")
	text_draw_tab_settings_05 = localize_ko("Song stats...")
	text_draw_tab_settings_06 = localize_ko("MIDI device manager")
	text_draw_tab_settings_07 = localize_ko("Preferences...")
	text_draw_tab_help_title = localize_ko("Help")
	text_draw_tab_help_01 = localize_ko("Tutorial videos")
	text_draw_tab_help_02 = localize_ko("View all")
	text_draw_tab_help_03 = localize_ko("Website...")
	text_draw_tab_help_04 = "GitHub..."
	text_draw_tab_help_05 = localize_ko("Discord server...")
	text_draw_tab_help_06 = localize_ko("Report a bug...")
	text_draw_tab_help_07 = localize_ko("Changelist...")
	text_draw_tab_help_08 = localize_ko("About...")
	text_draw_icon_new_song = localize_ko("New song")
	text_draw_icon_open_song = localize_ko("Open song")
	text_draw_icon_save_song = localize_ko("Save song")
	text_draw_icon_play_pause = localize_ko("Play / Pause song")
	text_draw_icon_stop_song = localize_ko("Stop song")
	text_draw_icon_rewind_song = localize_ko("Rewind song")
	text_draw_icon_fast_forward = localize_ko("Fast-forward song")
	text_draw_icon_record = localize_ko("Record key presses")
	text_draw_icon_toggle_loop = localize_ko("Toggle looping")
	text_draw_icon_toggle_metronome = localize_ko("Toggle metronome")
	text_draw_icon_edit_key = localize_ko("Edit note key")
	text_draw_icon_edit_velocity = localize_ko("Edit note velocity")
	text_draw_icon_edit_panning = localize_ko("Edit note panning")
	text_draw_icon_edit_pitch = localize_ko("Edit note pitch")
	text_draw_icon_change_to = localize_ko("Change instrument to ")
	text_draw_icon_less_ins = localize_ko("Less instruments")
	text_draw_icon_more_ins = localize_ko("More instruments...")
	text_draw_icon_undo = localize_ko("Undo the last change")
	text_draw_icon_redo = localize_ko("Redo the last undo")
	text_draw_icon_copy = localize_ko("Copy the selected note blocks")
	text_draw_icon_cut = localize_ko("Cut the selected note blocks")
	text_draw_icon_paste = localize_ko("Paste the copied note blocks")
	text_draw_icon_delete = localize_ko("Delete the selected note blocks")
	text_draw_icon_song_info = localize_ko("View song info")
	text_draw_icon_properties = localize_ko("Edit song properties")
	text_draw_icon_instruments = localize_ko("Edit instruments")
	text_draw_icon_midi_manager = localize_ko("MIDI device manager")
	text_draw_icon_tutorial = localize_ko("Watch tutorial videos")
	text_draw_icon_website = localize_ko("Visit the Note Block Studio website")
	text_draw_master_vol = localize_ko("Master Volume: ")
	text_draw_minecraft_compatible = localize_ko("Fully compatible")
	text_draw_minecraft_compatible_popup = localize_ko("This song is compatible with both schematics and data packs.\n(Click for more info.)")
	text_draw_minecraft_datapack = localize_ko("Data pack only")
	text_draw_minecraft_datapack_popup = localize_ko("This song is only compatible with data packs.\n(Click for more info.)")
	text_draw_minecraft_resource = localize_ko("Resource pack only")
	text_draw_minecraft_resource_popup = localize_ko("This song is compatible with data packs using a resource pack.\n(Click for more info.)")
	text_draw_status_instrument = localize_ko("Instrument: ")
	text_draw_status_key = localize_ko("Key: ")
	text_draw_status_tick = localize_ko("Tick: ")
	text_draw_status_layer = localize_ko("Layer: ")
	text_draw_status_selected = localize_ko("Selected: ")
	text_draw_status_none = localize_ko("None")
	text_draw_status_velocity = localize_ko("Velocity: ")
	text_draw_status_panning = localize_ko("Panning: ")
	text_draw_status_pitch = localize_ko("Pitch: ")
	text_draw_status_cents = localize_ko(" cents")
	text_draw_status_autosave = localize_ko("Next auto-save: ")
	text_draw_status_sounds = localize_ko("Sounds: ")
	text_draw_status_midi = localize_ko("MIDI devices: ")
	text_draw_status_midi_none = localize_ko("No connected MIDI devices")
	text_draw_player_song_position = localize_ko("Song Position")
	text_draw_time_pos = localize_ko("Position of the marker in bars, beats and sixteenths.")
	text_draw_time_tempobpm = localize_ko("Tempo of the song (measured in beats per minute).\nClick and drag to change. Click to enter value. Right-click for more options.")
	text_draw_time_tempotps = localize_ko("Tempo of the song (measured in ticks per second).\nClick and drag to change. Click to enter value. Right-click for more options.")
	text_draw_time_tempotip = localize_ko("Tip: click the tempo box\nto enter a value!")
	text_draw_tab_tempo_01 = localize_ko("Ticks per second (t/s)")
	text_draw_tab_tempo_02 = localize_ko("Beats per minute (BPM)")
	text_draw_tab_tempo_03 = localize_ko("Tempo tapper...")
	text_draw_time_tempotip_done = localize_ko("Way to go!")
	text_draw_update_title = localize_ko("Update")
	text_draw_update = localize_ko("Downloading update...")

	text_dragvalue_no_limit = localize_ko("No limit")

	text_menu_click_no_file = localize_ko("Could not find file:")
	text_menu_click_no_file_name = localize_ko("Error")
	text_menu_click_transpose = localize_ko("Transpose selected notes so that they fall within Minecraft's 2 octaves?")
	text_menu_click_transpose_name = localize_ko("Transpose notes")

	text_check_updates_available_01 = localize_ko("Version ")
	text_check_updates_available_02 = localize_ko(" is available! Do you want to download it?")
	text_check_updates_available_name = localize_ko("Update available!")

	text_get_update_complete = localize_ko("Download complete! Click OK to begin installing the update.")
	text_get_update_fail = localize_ko("Failed to download update. Do you want to open the Note Block Studio website and update manually?")
	text_get_update_fail_name = localize_ko("Failed")

	text_log_init_no_access = localize_ko("Could not access file directory. Try running in administrator mode or re-install.")

	text_mp3_export_name = localize_ko("Export MP3")
	text_mp3_export_error = localize_ko("There was an error when saving as MP3.\nError code: ")
	text_mp3_export_error_name = localize_ko("Error")
	text_mp3_export_complete = localize_ko("MP3 saved! Do you want to open it?")
	text_mp3_export_complete_name = localize_ko("MP3 Export")

	text_datapack_export_name = localize_ko("Data Pack Export")
	text_datapack_export_folder = localize_ko("Data Pack Folder")
	text_datapack_export_complete_01 = localize_ko("Data pack saved!")
	text_datapack_export_complete_02 = localize_ko("To play the song in-game, use: ")
	text_datapack_export_complete_03 = localize_ko("If you wish to uninstall it from")
	text_datapack_export_complete_04 = localize_ko("your world, run: ")
	text_datapack_export_complete_05 = localize_ko("and then remove it from the ")
	text_datapack_export_complete_06 = localize_ko("'datapacks' folder.")
	text_datapack_export_complete_name = localize_ko("Data Pack Export")

	text_datapack_getextranotes_name = localize_ko("Save extra notes for data pack")
	text_datapack_getextranotes_fname = localize_ko("Extra Note Blocks")
	text_datapack_getextranotes_complete = localize_ko("Resource pack saved successfully!")
	text_datapack_getextranotes_complete_name = localize_ko("Saved")

	text_datapack_getinstextures_name = localize_ko("Replaces instrument blocks with note block textures.")
	text_datapack_getinstextures_fname = localize_ko("Note Block Textures")
	text_datapack_getinstextures_complete = localize_ko("Resource pack saved successfully!")
	text_datapack_getinstextures_complete_name = localize_ko("Saved")
	text_datapack_getinstextures_error = localize_ko("File not found!")
	text_datapack_getinstextures_error_name = localize_ko("Error")

	text_confirm_title = localize_ko("Confirm")
	text_confirm_save = localize_ko("Do you want to save the song?")
	text_confirm_save_quit = localize_ko("Do you want to save the song before quitting?")
	text_confirm_save_in = localize_ko("Do you want to save the changes made in ")
	text_confirm_save_in_q = "?"
	text_confirm_save_in_quit = localize_ko("Do you want to save the changes made in ")
	text_confirm_save_in_quit_q = localize_ko(" before quitting?")
	
	text_instrument_change_name = localize_ko("Load sound file")
	
	text_instrument_load_error_01 = localize_ko("Couldn't load the file ")
	text_instrument_load_error_02 = localize_ko("! Error: ")
	text_instrument_load_error_name = localize_ko("Error")
	
	text_load_instruments_title = localize_ko("Load instruments from song")
	text_load_instruments_version_01 = localize_ko("Warning: You are opening an NBS file created in a later version of Note Block Studio.\nPlease save the song as a version ")
	text_load_instruments_version_02 = localize_ko(" file or lower via the Save Options menu.")
	text_load_instruments_error_name = localize_ko("Error")
	text_load_instruments_error = localize_ko("This file does not contain any custom instruments.")
	
	text_pack_instruments_name = localize_ko("Pack instruments to ZIP file")
	text_pack_instruments_complete = localize_ko(" instrument")
	text_pack_instruments_complete_single = localize_ko(" was")
	text_pack_instruments_complete_multiple = localize_ko("s were")
	text_pack_instruments_complete_saved = localize_ko(" saved!")
	text_pack_instruments_complete_name = localize_ko("Pack instruments")
	
	text_load_song_name = localize_ko("Load song")
	text_load_song_error_name = localize_ko("Error")
	text_load_song_warning_name = localize_ko("Warning")
	text_load_song_wrong_format = localize_ko("Error: This file cannot be opened in this program.")
	text_load_song_old_format = localize_ko("Warning: You are opening an older NBS file. Saving this file will make it incompatible with older Note Block Studio versions.")
	text_load_song_new_format_01 = localize_ko("Warning: You are opening an NBS file created in a later version of Note Block Studio.\nPlease save the song as a version ")
	text_load_song_new_format_02 = localize_ko(" file or lower via the Save Options menu.")
	text_load_song_custom_ins_01 = localize_ko("This song uses custom instruments. However, some sounds could not be loaded:")
	text_load_song_custom_ins_02 = localize_ko("Make sure that you have put the sounds in the \"Sounds\" folder. Open Instrument settings?")
	
	text_pattern_export_name = localize_ko("Save pattern")
	
	text_pattern_import_name = localize_ko("Load pattern")
	text_pattern_import_wrong_format = localize_ko("Error: This file is not a pattern.")
	text_pattern_import_old_format = localize_ko("Warning: You are opening an older NBP file. Saving this file will make it incompatible with older Note Block Studio versions.")
	text_pattern_import_new_format = localize_ko("Warning: You are opening an NBP file created in a later version of Note Block Studio. It may crash when opening.")
	text_pattern_import_more_ins = localize_ko("There are more custom instruments in the pattern than what is loaded in the song!")
	
	text_save_song_name = localize_ko("Save song")
	text_save_song_msg = localize_ko("Song saved")
	
	text_open_midi_name = localize_ko("Import from MIDI")
	text_open_midi_mthd = localize_ko("Error loading MIDI file:\n\nFirst 4 bytes must be MThd.\n\nContinue anyway?")
	text_open_midi_header = localize_ko("Error loading MIDI file:\n\nHeader size must be 00 00 00 06")
	text_open_midi_wrong_format = localize_ko("Error loading MIDI file:\n\nFormat not supported.")
	text_open_midi_mtrk = localize_ko("Error loading MIDI file:\n\nTrack chunk must begin with MTrk.")
	text_open_midi_unknown = localize_ko("Error loading MIDI file:\n\nUnknown MIDI event")
	
	text_macro_chorus_error = localize_ko("There must be exactly two layers worth of note blocks in every applicable tick!")
	
	text_selection_transpose = localize_ko(" notes were edited.")
	text_selection_transpose_name = localize_ko("Transpose notes")
	
	text_add_block_manual_octave = localize_ko("NOTE: Since this block is outside the 2 octave limit, you won't be able to import it into Minecraft without a resource pack.\n\nThis warning will never be shown again.")
	text_add_block_manual_customins = localize_ko("NOTE: Since this block has a custom instrument, you won't be able to import it into Minecraft without mods or resource packs.\n\nThis warning will never be shown again.")
	
	text_get_mode_actions_key_01 = localize_ko("Transpose one octave up")
	text_get_mode_actions_key_02 = localize_ko("Transpose one octave down")
	text_get_mode_actions_key_03 = localize_ko("Transpose up")
	text_get_mode_actions_key_04 = localize_ko("Transpose down")
	text_get_mode_actions_vel_01 = localize_ko("Increase velocity by 10")
	text_get_mode_actions_vel_02 = localize_ko("Decrease velocity by 10")
	text_get_mode_actions_vel_03 = localize_ko("Increase velocity")
	text_get_mode_actions_vel_04 = localize_ko("Decrease velocity")
	text_get_mode_actions_vel_05 = localize_ko("Set velocity...")
	text_get_mode_actions_vel_06 = localize_ko("Reset velocity")
	text_get_mode_actions_pan_01 = localize_ko("Pan right by 10")
	text_get_mode_actions_pan_02 = localize_ko("Pan left by 10")
	text_get_mode_actions_pan_03 = localize_ko("Pan right")
	text_get_mode_actions_pan_04 = localize_ko("Pan left")
	text_get_mode_actions_pan_05 = localize_ko("Set panning...")
	text_get_mode_actions_pan_06 = localize_ko("Reset panning")
	text_get_mode_actions_pit_01 = localize_ko("Detune +10 cents")
	text_get_mode_actions_pit_02 = localize_ko("Detune -10 cents")
	text_get_mode_actions_pit_03 = localize_ko("Detune +1 cent")
	text_get_mode_actions_pit_04 = localize_ko("Detune -1 cent")
	text_get_mode_actions_pit_05 = localize_ko("Set pitch...")
	text_get_mode_actions_pit_06 = localize_ko("Reset pitch")
	
	text_branch_export_name = localize_ko("Export Branch Schematic")
	text_branch_export_error = localize_ko("Error: Some notes are out of range!\nFix the fine pitch, or change it to a custom instrument with a higher/lower sound.")
	
	text_calculate_size_version = localize_ko("The exported schematic is currently only compatible with Minecraft: Java Edition 1.12 and below. To import it in 1.13 and above, please use the export to structure block function.\n\nThis warning will never be shown again.")
	text_calculate_size_name = localize_ko("Minecraft Compatibility")
	text_calculate_size_octave = localize_ko("Some note blocks are outside of Minecraft's 2 octave limit. Do you want to export a Schematic anyway, ignoring the affected blocks?")
	text_calculate_size_customins = localize_ko("Some note blocks have a custom instrument assigned to them. Export anyway?")
	text_calculate_size_pitch = localize_ko("Some note blocks have fine pitch tuning, which isn't supported in note blocks. Export anyway?")
	text_calculate_size_tempo = localize_ko("The tempo of the song is not compatible with Minecraft. As a result, the playback speed of the song in-game will differ from the one in the program.")
	text_calculate_size_tempo_name = localize_ko("Tempo")
	text_calculate_size_noblocks = localize_ko("There are no blocks to export!")
	
	text_schematic_export_name = localize_ko("Export Schematic")
	text_schematic_export_complete = localize_ko("Schematic saved!")
	text_schematic_export_complete_name = localize_ko("Schematic Export")
	
	text_open_schematic_name = localize_ko("Import from Schematic")
	text_open_schematic_file = localize_ko("Failed to load Schematic.\n\nERROR: Not a Schematic file.")
	text_open_schematic_size = localize_ko("Failed to load Schematic.\n\nERROR: Invalid size.")
	text_open_schematic_block = localize_ko("Failed to load Schematic.\n\nERROR: No Blocks array found.")
	text_open_schematic_data = localize_ko("Failed to load Schematic.\n\nERROR: No Data array found.")
	text_open_schematic_noblocks = localize_ko("Couldn't find any note blocks in the Schematic!")
	text_open_schematic_noinputs = localize_ko("The Schematic did not include any supported inputs.\nSupported inputs are:\n\n* Buttons\n* Levers")
	text_open_schematic_noconnect = localize_ko("None of the note blocks in the Schematic could be added. This could be to none of them being connected to any inputs (buttons or levers).")
	text_open_schematic_moreinputs = localize_ko("The Schematic contained more than one input.\n\nAs a result, the songs of the inputs have been put after each other.")
	text_open_schematic_moreinputs_name = localize_ko("Schematic import")
	
	text_window_about_name = localize_ko("About")
	text_window_about_local_release = localize_ko("Version Local Release")
	text_window_about_version = localize_ko("Version ")
	text_window_about_released = localize_ko(" - Released ")
	text_window_about_description = localize_ko("\n\nThis program is a continuation of\n Minecraft Note Block Studio, \ncreated by David Andrei. \n\nThis product is not affiliated with\nMojang Studios, Microsoft Studios\nor the game Minecraft.")
	text_window_about_website = localize_ko("Website")
	text_window_about_github = "GitHub"
	text_window_about_discord = "Discord"
	
	text_window_branch_export_name = localize_ko("Branch Export")
	text_window_branch_export_tab_design = localize_ko("Design")
	text_window_branch_export_tab_blocks = localize_ko("Blocks")
	text_window_branch_export_remember = localize_ko("Remember changes")
	text_window_branch_export_remember_popup = localize_ko("Whether to use these settings the\nnext time you export a branch.")
	text_window_branch_export_layout = localize_ko("Layout:")
	text_window_branch_export_all = localize_ko("All")
	text_window_branch_export_all_popup = localize_ko("Exports all notes.")
	text_window_branch_export_center = localize_ko("Center")
	text_window_branch_export_center_popup = localize_ko("Only exports notes which have no panning values.")
	text_window_branch_export_left = localize_ko("Left")
	text_window_branch_export_left_popup = localize_ko("Only exports notes that have left stereo values.")
	text_window_branch_export_right = localize_ko("Right")
	text_window_branch_export_right_popup = localize_ko("Only exports notes that have right stereo values.")
	text_window_branch_export_polyphony = localize_ko("Polyphony:")
	text_window_branch_export_main_layer = localize_ko("Main layer:")
	text_window_branch_export_chord_layer_1 = localize_ko("Chord layer 1:")
	text_window_branch_export_chord_layer_2 = localize_ko("Chord layer 2:")
	text_window_branch_export_none = localize_ko("None")
	text_window_branch_export_velocity = localize_ko("Enable velocity")
	text_window_branch_export_velocity_popup = localize_ko("Whether to position the note blocks differently due to their velocity.\nIt's recommended that each layer's velocity should be the same when polyphony is higher than 1.")
	text_window_branch_export_circuitry = localize_ko("Export circuitry")
	text_window_branch_export_circuitry_popup = localize_ko("Whether to export the ground, repeaters, and redstone.")
	text_window_branch_export_size = localize_ko("Size:")
	text_window_branch_export_range = localize_ko("Range:")
	text_window_branch_export_start_tick = localize_ko("Start Tick")
	text_window_branch_export_end_tick = localize_ko("End Tick")
	text_window_branch_export_instrument = localize_ko("Instrument")
	text_window_branch_export_instrument_popup = localize_ko("The name of the instrument.")
	text_window_branch_export_block = localize_ko("Block")
	text_window_branch_export_block_popup = localize_ko("The ID of the block that should be placed\nbelow note blocks of the instrument.")
	text_window_branch_export_block_name = localize_ko("Block name")
	text_window_branch_export_block_name_popup = localize_ko("The name of the block that should be\nplaced below note blocks of the instrument.")
	text_window_branch_export_circuitry_block = localize_ko("Block for circuitry: ")
	text_window_branch_export_circuitry_block_popup = localize_ko("The block that should be used for the circuitry.")
	text_window_branch_export_export = localize_ko("Export")
	text_window_branch_export_noblocks = localize_ko("There are no blocks to export!")
	text_window_branch_export_norange = localize_ko("Please enter a range!")
	text_window_branch_export_starting_tick = localize_ko("Starting tick must be lower than ending tick!")
	text_window_branch_export_ending_tick = localize_ko("The ending tick is larger than the song!\nThe size of the song is ")
	text_window_branch_export_ending_tick_period = "."
	text_window_branch_export_default = localize_ko("Use default")
	text_window_branch_export_confirm = localize_ko("Are you sure?")
	text_window_branch_export_confirm_name = localize_ko("Confirm")
	text_window_branch_export_wool = localize_ko("Wool")
	text_window_branch_export_glass = localize_ko("Stained glass")
	text_window_branch_export_terracotta = localize_ko("Colored Terracotta")
}

/// @description Refresh built-in instrument labels without touching custom names or audio.
function localize_instrument_names() {
	var names = [
		localize_ko("Harp"), localize_ko("Double Bass"), localize_ko("Bass Drum"),
		localize_ko("Snare Drum"), localize_ko("Click"), localize_ko("Guitar"),
		localize_ko("Flute"), localize_ko("Bell"), localize_ko("Chime"),
		localize_ko("Xylophone"), localize_ko("Iron Xylophone"), localize_ko("Cow Bell"),
		localize_ko("Didgeridoo"), localize_ko("Bit"), localize_ko("Banjo"),
		localize_ko("Pling"), localize_ko("Trumpet"), localize_ko("Exposed Trumpet"),
		localize_ko("Weathered Trumpet"), localize_ko("Oxidized Trumpet")
	];
	for (var i = 0; i < min(array_length(original_instruments), array_length(names)); i++) {
		original_instruments[i].name = names[i];
	}
}
